name: Build Axevent Applications
on:
  push:
    paths:
      - 'axevent/**'
      - '!axevent/**/README.md'
      - '.github/workflows/axevent.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Send event application
        run: |
          imagetag=send-event:1.0
          docker image rm -f $imagetag
          cd axevent/send_event
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          cd ..
          mkdir -p acap3/examples/axevent/send_event/build
          cp axevent/send_event/build/send_event_1_0_0_armv7hf.eap acap3/examples/axevent/send_event/build/send_event_1_0_0_armv7hf.eap

      - name: Build subscribe to event application
        run: |
          imagetag=subscribe-to-event:1.0
          docker image rm -f $imagetag
          cd axevent/subscribe_to_event
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          cd ..
          mkdir -p acap3/examples/axevent/subscribe_to_event/build
          cp axevent/subscribe_to_event/build/subscribe_to_event_1_0_0_armv7hf.eap acap3/examples/axevent/subscribe_to_event/build/subscribe_to_event_1_0_0_armv7hf.eap

      - name: Build subscribe to events application
        run: |
          imagetag=subscribe-to-events:1.0
          docker image rm -f $imagetag
          cd axevent/subscribe_to_events
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          cd ..
          mkdir -p acap3/examples/axevent/subscribe_to_events/build
          cp axevent/subscribe_to_events/build/subscribe_to_events_1_0_0_armv7hf.eap acap3/examples/axevent/subscribe_to_events/build/subscribe_to_events_1_0_0_armv7hf.eap
