name: Build Axevent Applications
on:
  push:
     paths:
      - 'axevent/**'
      - '.github/workflows/Axevent.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Send event application
      run: |
        cd axevent/send_event
        docker build --tag send-event:1.0 .
        docker cp $(docker create send-event:1.0):/opt/app ./build
        cd ../..

    - name: Build subscribe to event application
      run: |
        cd axevent/subscribe_to_event
        docker build --tag subscribe-to-event:1.0 .
        docker cp $(docker create subscribe-to-event:1.0):/opt/app ./build
        cd ../..

    - name: Build subscribe to events application
      run: |
        cd axevent/subscribe_to_events
        docker build --tag subscribe-to-events:1.0 .
        docker cp $(docker create subscribe-to-events:1.0):/opt/app ./build
        cd ../..
