name: Build axevent applications
on:
  push:
    paths:
      - 'axevent/**'
      - '!axevent/**/README.md'
      - '.github/workflows/axevent.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXNAME: axevent
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: send_event
          imagetag: send-event:1.0
          eapfile: send_event_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/$example
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../..
          mkdir -p $EXDIR/$example/build
          cp $EXNAME/$example/build/$eapfile $EXDIR/$example/build/$eapfile

      - name: Build ${{ env.example }} application
        env:
          example: subscribe_to_event
          imagetag: subscribe-to-event:1.0
          eapfile: subscribe_to_event_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/$example
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../..
          mkdir -p $EXDIR/$example/build
          cp $EXNAME/$example/build/$eapfile $EXDIR/$example/build/$eapfile

      - name: Build ${{ env.example }} application
        env:
          example: subscribe_to_events
          imagetag: subscribe-to-events:1.0
          eapfile: subscribe_to_events_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/$example
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../..
          mkdir -p $EXDIR/$example/build
          cp $EXNAME/$example/build/$eapfile $EXDIR/$example/build/$eapfile
