name: Build Axevent Applications
on:
  push:
     paths:
      - 'axevent/**'
      - '.github/workflows/Axevent.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    - name: Build Send event application
      run: |    
        imagetag=send-event:1.0
        docker image rm -f $imagetag
        cd axevent/send_event
        docker build --no-cache --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
    
         
    - name: Build subscribe to event application
      run: |
        imagetag=subscribe-to-event:1.0
        docker image rm -f $imagetag
        cd axevent/subscribe_to_event
        docker build --no-cache --tag $imagetag .
        docker cp $(docker create subscribe-to-event:1.0):/opt/app ./build

        
    - name: Build subscribe to events application
      run: |     
        imagetag=subscribe-to-events:1.0
        docker image rm -f $imagetag
        cd axevent/subscribe_to_events
        docker build --no-cache --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
