name: Build Axevent Applications
on:
  push:
     paths:
      - 'axevent/**'
      - '.github/workflows/Axevent.yml'
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    # Build Send event application
    - name: Build Send event application
      run: |    
        cd axevent/send_event
        docker build --tag send-event:1.0 .
        docker cp $(docker create send-event:1.0):/opt/app ./build
        cd ..
        cd ..
    
         
   # Build Subscribe to event application
    - name: Build subscribe to event application
      run: |
        cd axevent/subscribe_to_event
        docker build --tag subscribe-to-event:1.0 .
        docker cp $(docker create subscribe-to-event:1.0):/opt/app ./build
        cd ..
        cd ..

        
     # Build Subscribe to events application
    - name: Build subscribe to events application
      run: |     
        cd axevent/subscribe_to_events
        docker build --tag subscribe-to-events:1.0 .
        docker cp $(docker create subscribe-to-events:1.0):/opt/app ./build
        cd ..
        cd ..

