name: Build axoverlay handler Applications
on:
  push:
     paths:
      - 'axoverlay/**'
      - '.github/workflows/axoverlay.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Axoverlay application
      run: |
        cd axoverlay
        docker build --tag axoverlay:1.0 .
        docker cp $(docker create axoverlay:1.0 .):/opt/app ./build
