name: Build axoverlay Applications
on:
  push:
    paths:
      - 'axoverlay/**'
      - '!axoverlay/README.md'
      - '.github/workflows/axoverlay.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Axoverlay application
        run: |
          imagetag=axoverlay:1.0
          docker image rm -f $imagetag
          cd axoverlay
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag .):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/axoverlay/build
          cp axoverlay/build/axoverlay_1_0_0_armv7hf.eap acap3/examples/axoverlay/build/axoverlay_1_0_0_armv7hf.eap
          ls acap3/examples/axoverlay/build
