name: Build Applications

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    # Run build script larod application
    - name: Build larod application
      run: |
        cd larod
        docker build --tag larod-simple-app:1.0 .
        docker cp $(docker create larod-simple-app:1.0):/opt/app ./build
        cd ..
        
    # Save larop application *.eap file as artifact
    - uses: actions/upload-artifact@master
      with:
        name: larod application
        path: larod/build/
        
    # Build VDO stream application
    - name: Build vdo stream application
      run: |        
        cd vdostream
        docker build --tag axisecp/vdoencodeclient:1.0 .
        docker cp $(docker create axisecp/vdoencodeclient:1.0):/opt/app ./build
        cd ..
        
    # Save VDO stream application *.eap file as artifact
    - uses: actions/upload-artifact@master
      with:
        name: vdo stream application
        path: vdostream/build/
        

