name: Build hello-world Applications
on:
  push:
    paths:
      - 'hello-world/**'
      - '!hello-world/README.md'
      - '.github/workflows/hello-world.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build hello-world application
        run: |
          imagetag=hello-world:1.0
          docker image rm -f $imagetag
          cd hello-world
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/hello-world/build
          cp hello-world/build/hello_world_1_0_0_armv7hf.eap acap3/examples/hello-world/build/hello_world_1_0_0_armv7hf.eap
          ls acap3/examples/hello-world/build
