name: Build hello-world application
on:
  push:
    paths:
      - 'hello-world/**'
      - '!hello-world/README.md'
      - '.github/workflows/hello-world.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap3-examples
      EXNAME: hello-world
      EAPNAME: hello_world
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
          eapfile: ${{ env.EAPNAME }}_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p $EXDIR/build
          cp $EXNAME/build/$eapfile $EXDIR/build/$eapfile
          docker image rm -f $imagetag
