name: Build hello-world Applications
on:
  push:
     paths:
      - 'hello-world/**'
      - '.github/workflows/hello-world.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build hello-world application
      run: |
        cd hello-world
        docker build --tag hello_world:1.0 .
        docker cp $(docker create hello_world:1.0 .):/opt/app ./build
