name: Build larod Applications
on:
  push:
     paths:
      - 'larod/**'
      - '.github/workflows/larod.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    - name: Build larod application
      run: |
        imagetag=larod-simple-app:1.0
        docker image rm -f $imagetag
        export DOCKER_CONFIG="$WORKSPACE/.docker"
        mkdir -p "$DOCKER_CONFIG"
        echo '{"proxies":{ "default":{"httpProxy": "http://wwwproxy.se.axis.com:3128", "httpsProxy": "http://wwwproxy.se.axis.com:3128"}}}' > "$DOCKER_CONFIG/config.json"
        docker login -u ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASS }}

        cd larod
        docker build --no-cache --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
