name: Build larod Applications
on:
  push:
     paths:
      - 'larod/**'
      - '.github/workflows/larod.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    # Run build script larod application
    - name: Build larod application
      run: |
        export http_proxy=http://wwwproxy.se.axis.com:3128
        export https_proxy=http://wwwproxy.se.axis.com:3128
        docker login -u ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASS }}
        
        cd larod
        docker build --tag larod-simple-app:1.0 .
        docker cp $(docker create larod-simple-app:1.0):/opt/app ./build
