name: Build larod Applications
on:
  push:
     paths:
      - 'larod/**'
      - '.github/workflows/larod.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build larod application
      run: |
        cd larod
        docker build --tag larod-simple-app:1.0 .
        docker cp $(docker create larod-simple-app:1.0):/opt/app ./build
