name: Build larod Applications
on:
  push:
    paths:
      - 'larod/**'
      - '!larod/README.md'
      - '.github/workflows/larod.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build larod application
        run: |
          imagetag=larod-simple-app:1.0
          docker image rm -f $imagetag
          cd larod
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/larod/build
          cp larod/build/larod-simple-app_1_0_0_armv7hf.eap acap3/examples/larod/build/larod-simple-app_1_0_0_armv7hf.eap
