name: Build licensekey handler Applications
on:
  push:
     paths:
      - 'licensekey/**'
      - '.github/workflows/licensekey.yml'
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    #Build Licensekey handler application
    - name: Build licensekey handler application
      run: |
        cd licensekey
        docker build --tag licensekey_handler:1.0 .
        docker cp $(docker create licensekey_handler:1.0 .):/opt/app ./build
        cd ..
        mkdir -p acap3/examples/licensekey/build
        cp licensekey/build/licensekey_handler_1_0_0_armv7hf.eap acap3/examples/licensekey/build/licensekey_handler_1_0_0_armv7hf.eap
        ls acap3/examples/licensekey/build
