name: Build licensekey handler Applications
on:
  push:
     paths:
      - 'licensekey/**'
      - '.github/workflows/licensekey.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build licensekey handler application
      run: |
        cd licensekey
        docker build --tag licensekey_handler:1.0 .
        docker cp $(docker create licensekey_handler:1.0 .):/opt/app ./build

