name: Lint Code Base

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true

      - name: Check that linter symbolic links exist in top directory
        run: |
          missing_symlinks=""
          symlinks="\
            .hadolint.yml \
            .markdownlint.yml \
            .yamllint.yml \
          "

          for syml in $symlinks
          do
            [ -L $syml ] && [ -f $syml ] || {
              missing_symlinks="$syml $missing_symlinks"
            }
          done

          [ -z "$missing_symlinks" ] || {
            echo "ERROR: Missing linter symlinks"
            echo "The following symlinks are missing in top directory"
            for msyml in $missing_symlinks
            do
              echo "* $msyml"
            done
            exit 1
          }
