name: Build object detection application
on:
  push:
    paths:
      - 'object-detection/**'
      - '!object-detection/README.md'
      - '.github/workflows/object-detection.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build object-detection application
        run: |
          imagetag=object-detection-acap:1.0
          docker image rm -f $imagetag
          cd object-detection
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/object-detection/build
          cp object-detection/build/object_detection_app_1_0_0_armv7hf.eap acap3/examples/object-detection/build/object_detection_app_1_0_0_armv7hf.eap
