name: Build object-detection application
on:
  workflow_dispatch:
  push:
    paths:
      - 'object-detection/**'
      - '!object-detection/README.md'
      - '.github/workflows/object-detection.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armv7hf
            chip: cpu
            axis-os: 10.12.153
          - arch: armv7hf
            chip: edgetpu
            axis-os: 10.12.153
          - arch: aarch64
            chip: artpec8
            axis-os: 10.12.153
    env:
      EXREPO: acap3-examples
      EXNAME: object-detection
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}-${{ matrix.chip }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}-${{ matrix.chip }}:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          cp app/manifest.json.${{ matrix.chip }} app/manifest.json
          docker build --no-cache --build-arg CHIP=${{ matrix.chip }} --build-arg ARCH=${{ matrix.arch }} --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build_${{ matrix.chip }}
          cd ..
          docker image rm -f $imagetag
