name: Build tensorflow-to-larod application
on:
  push:
    paths:
      - 'tensorflow-to-larod/**'
      - '!tensorflow-to-larod/README.md'
      - '.github/workflows/tensorflow-to-larod.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap3-examples
      EXNAME: tensorflow-to-larod
      EAPNAME: tensorflow_to_larod_app
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
          eapfile: ${{ env.EAPNAME }}_1_0_0_armv7hf.eap
        run: |
          envname=tensorflow-to-larod
          appimagename=tensorflow-app-image
          docker image rm -f $imagetag
          docker image rm -f $envname:latest
          docker rm -f $appimagename
          cd $EXNAME
          ./build_env.sh
          docker run -v /var/run/docker.sock:/var/run/docker.sock --network host --name $appimagename $envname /bin/bash ./build_acap.sh $imagetag
          docker cp $appimagename:/env/build ./build
          docker stop $appimagename
          docker rm -f $appimagename
          cd ..
          mkdir -p $EXDIR/build
          cp $EXNAME/build/$eapfile $EXDIR/build/$eapfile
          docker image rm -f $imagetag
