name: Build tensorflow-to-larod application
on:
  workflow_dispatch:
  push:
    paths:
      - 'tensorflow-to-larod/**'
      - '!tensorflow-to-larod/README.md'
      - '.github/workflows/tensorflow-to-larod.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        axis-os: ["10.12.153"]
    env:
      EXREPO: acap3-examples
      EXNAME: tensorflow-to-larod
      EXDIR: acap/examples/$EXNAME
      arch: armv7hf
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.EXNAME }} application
        env:
          env_name: ${{ env.EXREPO }}-${{ env.EXNAME }}-env
          imagetag_env: ${{ env.EXREPO }}_${{ env.EXNAME }}_environment:${{ env.arch }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}${{ env.arch }}
        run: |
          docker image rm -f $imagetag
          docker image rm -f $imagetag_env
          docker rm -f $env_name
          cd $EXNAME
          ./build_env.sh $imagetag_env
          docker run -v /var/run/docker.sock:/var/run/docker.sock --network host --name $env_name $imagetag_env /bin/bash ./build_acap.sh $imagetag
          docker cp $env_name:/env/build ./build
          docker stop $env_name
          docker rm -f $env_name
          cd ..
          docker image rm -f $imagetag
