name: Build tensorflow-to-larod Applications
on:
  push:
     paths:
      - 'tensorflow-to-larod/**'
      - '.github/workflows/tensorflow-to-larod.yml'
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    #Build tensorflow-to-larod application
    - name: Build tensorflow-to-larod application
      run: |
        cd tensorflow-to-larod
        ./build_env.sh
        docker run -v /var/run/docker.sock:/var/run/docker.sock --network host --name tensorflow_env5 tensorflow_to_larod /bin/bash ./build_acap.sh tensorflow_to_larod_acap:1.0
        docker cp tensorflow_env5:/env/build/tensorflow_to_larod_app_1_0_0_armv7hf.eap tensorflow_to_larod.eap
        docker stop tensorflow_env5
        docker rm tensorflow_env5
