name: Build tensorflow-to-larod application
on:
  workflow_dispatch:
  push:
    paths:
      - 'tensorflow-to-larod/**'
      - '!tensorflow-to-larod/README.md'
      - '.github/workflows/tensorflow-to-larod.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap3-examples
      EXNAME: tensorflow-to-larod
      EAPNAME: tensorflow_to_larod_app
      EXDIR: acap/examples/$EXNAME
      arch: armv7hf
    steps:
      - uses: actions/checkout@v3

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          env_name: ${{ env.EXREPO }}-${{ env.EXNAME }}-env
          imagetag_env: ${{ env.EXREPO }}_${{ env.EXNAME }}_environement:1.0
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
          eapfile: ${{ env.EAPNAME }}_1_0_0_${{ env.arch }}.eap
        run: |
          docker image rm -f $imagetag
          docker image rm -f $imagetag_env
          docker rm -f $env_name
          cd $EXNAME
          ./build_env.sh $imagetag_env
          docker run -v /var/run/docker.sock:/var/run/docker.sock --network host --name $env_name $imagetag_env /bin/bash ./build_acap.sh $imagetag
          docker cp $env_name:/env/build ./build
          docker stop $env_name
          docker rm -f $env_name
          cd ..
          docker image rm -f $imagetag
