name: Build using opencv application
on:
  push:
    paths:
      - 'using-opencv/**'
      - '!using-opencv/README.md'
      - '.github/workflows/using-opencv.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build using-opencv application
        run: |
          imagetag=using-opencv
          docker image rm -f "${imagetag}:latest"
          cd using-opencv
          ./build.sh $imagetag
          cd ..
          mkdir -p acap3/examples/using-opencv/build
          cp using-opencv/build/opencv_example_1_0_0_armv7hf.eap acap3/examples/using-opencv/build/opencv_example_1_0_0_armv7hf.eap
