name: Build utility libraries Application
on:
  push:
    paths:
      - 'utility-libraries/**'
      - '!utility-libraries/**/README.md'
      - '.github/workflows/utility-libraries.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build curl library application
        run: |
          imagetag=utility-libraries:1.0
          docker image rm -f $imagetag
          cd utility-libraries/curl_example
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app/ ./build
          cd ../..
          mkdir -p acap3/examples/utility-libraries/curl_example/build
          cp utility-libraries/curl_example/build/curl_example_1_0_0_armv7hf.eap acap3/examples/utility-libraries/curl_example/build/curl_example_1_0_0_armv7hf.eap

      - name: Build custom library application
        run: |
          imagetag=utility-libraries:1.0
          docker image rm -f $imagetag
          cd utility-libraries/custom_lib_example
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app/ ./build
          cd ../..
          mkdir -p acap3/examples/utility-libraries/custom_lib_example/build
          cp utility-libraries/custom_lib_example/build/customlib_example_1_0_0_armv7hf.eap acap3/examples/utility-libraries/custom_lib_example/build/customlib_example_1_0_0_armv7hf.eap
