name: Build vdo-opencl-filtering Application
on:
  push:
    paths:
      - 'vdo-opencl-filtering/**'
      - '!vdo-opencl-filtering/README.md'
      - '.github/workflows/vdo-opencl-filtering.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build vdo-opencl-filtering application
        run: |
          imagetag=vdo_cl_filter_demo:1.0
          docker image rm -f $imagetag
          cd vdo-opencl-filtering
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/vdo-opencl-filtering/build
          cp vdo-opencl-filtering/build/vdo_cl_filter_demo_1_0_0_armv7hf.eap acap3/examples/vdo-opencl-filtering/build/vdo_cl_filter_demo_1_0_0_armv7hf.eap
