name: Build vdo-larod-preprocessing Applications
on:
  push:
     paths:
      - 'vdo-larod-preprocessing/**'
      - '.github/workflows/vdo-larod-preprocessing.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    - name: Build vdo-larod-preprocessing application to run on CPU
      run: |  
        imagetag=vdo-larod-preprocessing-cpu:1.0
        docker image rm -f $imagetag
        cd vdo-larod-preprocessing
        cp app/manifest.json.cpu app/manifest.json
        docker build --no-cache --build-arg CHIP=cpu --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
  
    - name: Build vdo-larod-preprocessing application to run on TPU
      run: |     
        imagetag=vdo-larod-preprocessing-tpu:1.0
        docker image rm -f $imagetag
        cd vdo-larod-preprocessing
        rm -rf build/
        cp app/manifest.json.edgetpu app/manifest.json
        docker build --no-cache --build-arg CHIP=edgetpu --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
 
