name: Build vdo larod Applications
on:
  push:
     paths:
      - 'vdo-larod/**'
      - '.github/workflows/vdo-larod.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    # Build VDO larod application to run on CPU
    - name: Build VDO larod application to run on CPU
      run: |
        cd vdo-larod
        cp app/package.conf.cpu app/package.conf
        docker build --tag vdo_larod_cpu:1.0 .
        docker cp $(docker create vdo_larod_cpu:1.0):/opt/app ./build

    # Build VDO larod application to run on TPU
    - name: Build VDO larod application to run on TPU
      run: |
        cd vdo-larod
        rm -rf build/
        cp app/package.conf.edgetpu app/package.conf
        docker build --tag vdo_larod_tpu:1.0 .
        docker cp $(docker create vdo_larod_tpu:1.0):/opt/app ./build
