name: Build vdo-opencl-filtering application
on:
  push:
    paths:
      - 'vdo-opencl-filtering/**'
      - '!vdo-opencl-filtering/README.md'
      - '.github/workflows/vdo-opencl-filtering.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap3-examples
      EXNAME: vdo-opencl-filtering
      EAPNAME: vdo_cl_filter_demo
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
          eapfile: ${{ env.EAPNAME }}_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p $EXDIR/build
          cp $EXNAME/build/$eapfile $EXDIR/build/$eapfile
          docker image rm -f $imagetag
