name: Build VDO OpenCL Filtering Application
on:
  push:
     paths:
      - 'vdo-opencl-filtering/**'
      - '.github/workflows/vdo-opencl-filtering.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148

    # Build VDO OpenCL Filtering application
    - name: Build VDO OpenCL Filtering application
      run: |
        imagetag=vdo_cl_filter_demo:1.0
        docker image rm -f $imagetag
        cd vdo-opencl-filtering
        docker build --no-cache --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
