name: Build vdostream Application
on:
  push:
    paths:
      - 'vdostream/**'
      - '!vdostream/README.md'
      - '.github/workflows/vdostream.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build vdo stream application
        run: |
          imagetag=vdoencodeclient:1.0
          docker image rm -f $imagetag
          cd vdostream
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/vdostream/build
          cp vdostream/build/vdoencodeclient_1_0_0_armv7hf.eap acap3/examples/vdostream/build/vdoencodeclient_1_0_0_armv7hf.eap
