name: Build vdostream Application
on:
  push:
    paths:
      - 'vdostream/**'
      - '!vdostream/README.md'
      - '.github/workflows/vdostream.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    - name: Build vdo stream application
      run: |        
        imagetag=vdoencodeclient:1.0
        docker image rm -f $imagetag
        cd vdostream
        docker build --no-cache --tag $imagetag .
        docker cp $(docker create $imagetag):/opt/app ./build
    
