name: Build vdostream application
on:
  push:
    paths:
      - 'vdostream/**'
      - '!vdostream/README.md'
      - '.github/workflows/vdostream.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXNAME: vdostream
      EAPNAME: vdoencodeclient
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXNAME }}:1.0
          eapfile: ${{ env.EAPNAME }}_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p $EXDIR/build
          cp $EXNAME/build/$eapfile $EXDIR/build/$eapfile
