name: Build vdostream application
on:
  workflow_dispatch:
  push:
    paths:
      - 'vdostream/**'
      - '!vdostream/README.md'
      - '.github/workflows/vdostream.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        axis-os: ["10.12.153"]
        arch: ["armv7hf", "aarch64"]
    env:
      EXREPO: acap3-examples
      EXNAME: vdostream
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.EXNAME }} application
        env:
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker build --no-cache --tag $imagetag --build-arg ARCH=${{ matrix.arch }} .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          docker image rm -f $imagetag
